use crate::api::types::ServerEntry;

/// Auto-assign tags based on server name, category, and known characteristics.
fn auto_tags(owner: &str, name: &str) -> Vec<String> {
    let mut tags = Vec::new();
    let cat = server_category(owner, name);

    // Category-based tags
    if cat.contains("Files") { tags.push("filesystem".into()); tags.push("files".into()); }
    if cat.contains("Databases") { tags.push("database".into()); tags.push("sql".into()); }
    if cat.contains("Dev Tools") { tags.push("developer".into()); tags.push("devtools".into()); }
    if cat.contains("Communication") { tags.push("messaging".into()); tags.push("communication".into()); }
    if cat.contains("Browser") { tags.push("browser".into()); tags.push("web".into()); tags.push("automation".into()); }
    if cat.contains("AI") { tags.push("ai".into()); tags.push("reasoning".into()); }
    if cat.contains("Utilities") { tags.push("utility".into()); }
    if cat.contains("Cloud") { tags.push("cloud".into()); tags.push("infrastructure".into()); }
    if cat.contains("Commerce") { tags.push("commerce".into()); }
    if cat.contains("Observability") { tags.push("monitoring".into()); tags.push("observability".into()); }
    if cat.contains("Productivity") { tags.push("productivity".into()); }
    if cat.contains("Design") { tags.push("design".into()); }

    // Name-based tags
    match name {
        "postgres" | "sqlite" | "neon" | "turso" | "astra-db" => { tags.push("sql".into()); }
        "redis" => { tags.push("nosql".into()); tags.push("cache".into()); }
        "github" | "gitlab" | "git" => { tags.push("git".into()); tags.push("vcs".into()); }
        "puppeteer" | "playwright" | "stagehand" | "firecrawl" => { tags.push("scraping".into()); }
        "docker" => { tags.push("containers".into()); }
        "fetch" => { tags.push("http".into()); tags.push("web".into()); }
        "memory" => { tags.push("knowledge-graph".into()); }
        "sequentialthinking" => { tags.push("planning".into()); }
        _ => {}
    }

    // Name-based heuristic tags for anything not yet matched
    if name.contains("search") { tags.push("search".into()); }
    if name.contains("web") { tags.push("web".into()); }
    if name.contains("api") { tags.push("api".into()); }
    if name.contains("cloud") { tags.push("cloud".into()); }
    if name.contains("ai") || name.contains("llm") || name.contains("model") {
        tags.push("ai".into());
    }

    // Official tag
    if owner == "modelcontextprotocol" {
        tags.push("official".into());
    }

    // Ensure every server gets at least one tag based on category
    if tags.is_empty() {
        tags.push("mcp".into());
    }

    tags.sort();
    tags.dedup();
    tags
}

/// Returns a curated list of well-known MCP servers for seeding the registry.
pub fn default_servers() -> Vec<ServerEntry> {
    let mut servers = vec![
        // ── Reference servers (official, from modelcontextprotocol/servers) ──
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "filesystem".into(),
            version: "2024.11.0".into(),
            description: "Secure file operations with configurable access controls".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-filesystem".into()],
            transport: "stdio".into(),
            tools: vec!["read_file".into(), "write_file".into(), "list_directory".into(), "create_directory".into(), "move_file".into(), "search_files".into(), "get_file_info".into(), "read_multiple_files".into()],
            resources: vec!["file://".into()],
            prompts: vec![],
            tags: vec![],
            downloads: 52000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "fetch".into(),
            version: "2024.11.0".into(),
            description: "Web content fetching and conversion for efficient LLM usage".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "uvx".into(),
            args: vec!["mcp-server-fetch".into()],
            transport: "stdio".into(),
            tools: vec!["fetch".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 38000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "memory".into(),
            version: "2024.11.0".into(),
            description: "Knowledge graph-based persistent memory system".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-memory".into()],
            transport: "stdio".into(),
            tools: vec!["create_entities".into(), "create_relations".into(), "add_observations".into(), "delete_entities".into(), "delete_observations".into(), "delete_relations".into(), "read_graph".into(), "search_nodes".into(), "open_nodes".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 35000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "sequentialthinking".into(),
            version: "2024.11.0".into(),
            description: "Dynamic and reflective problem-solving through thought sequences".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-sequential-thinking".into()],
            transport: "stdio".into(),
            tools: vec!["sequentialthinking".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 28000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "git".into(),
            version: "2024.11.0".into(),
            description: "Tools to read, search, and manipulate Git repositories".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "uvx".into(),
            args: vec!["mcp-server-git".into()],
            transport: "stdio".into(),
            tools: vec!["git_status".into(), "git_diff_unstaged".into(), "git_diff_staged".into(), "git_log".into(), "git_show".into(), "git_create_branch".into(), "git_checkout".into(), "git_commit".into(), "git_add".into(), "git_reset".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 31000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "time".into(),
            version: "2024.11.0".into(),
            description: "Time and timezone conversion capabilities".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "uvx".into(),
            args: vec!["mcp-server-time".into()],
            transport: "stdio".into(),
            tools: vec!["get_current_time".into(), "convert_time".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 18000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "everything".into(),
            version: "2024.11.0".into(),
            description: "Reference / test server with prompts, resources, and tools".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-everything".into()],
            transport: "stdio".into(),
            tools: vec!["echo".into(), "add".into(), "longRunningOperation".into(), "sampleLLM".into(), "getTinyImage".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 12000,
            created_at: None,
            updated_at: None,
        },

        // ── Archived reference servers ──
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "github".into(),
            version: "2024.11.0".into(),
            description: "Repository management, file operations, and GitHub API integration".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-github".into()],
            transport: "stdio".into(),
            tools: vec!["create_or_update_file".into(), "search_repositories".into(), "create_repository".into(), "get_file_contents".into(), "push_files".into(), "create_issue".into(), "create_pull_request".into(), "fork_repository".into(), "create_branch".into(), "list_commits".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 45000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "gitlab".into(),
            version: "2024.11.0".into(),
            description: "GitLab API, enabling project management".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-gitlab".into()],
            transport: "stdio".into(),
            tools: vec!["create_or_update_file".into(), "search_repositories".into(), "create_repository".into(), "get_file_contents".into(), "push_files".into(), "create_issue".into(), "create_merge_request".into(), "fork_repository".into(), "create_branch".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 15000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "slack".into(),
            version: "2024.11.0".into(),
            description: "Channel management and messaging capabilities for Slack".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-slack".into()],
            transport: "stdio".into(),
            tools: vec!["list_channels".into(), "post_message".into(), "reply_to_thread".into(), "add_reaction".into(), "get_channel_history".into(), "get_thread_replies".into(), "search_messages".into(), "get_users".into(), "get_user_profile".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 22000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "postgres".into(),
            version: "2024.11.0".into(),
            description: "Read-only database access with schema inspection for PostgreSQL".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-postgres".into()],
            transport: "stdio".into(),
            tools: vec!["query".into()],
            resources: vec!["postgres://".into()],
            prompts: vec![],
            tags: vec![],
            downloads: 25000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "sqlite".into(),
            version: "2024.11.0".into(),
            description: "Database interaction and business intelligence capabilities for SQLite".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "uvx".into(),
            args: vec!["mcp-server-sqlite".into()],
            transport: "stdio".into(),
            tools: vec!["read_query".into(), "write_query".into(), "create_table".into(), "list_tables".into(), "describe_table".into(), "append_insight".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 20000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "puppeteer".into(),
            version: "2024.11.0".into(),
            description: "Browser automation and web scraping via Puppeteer".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-puppeteer".into()],
            transport: "stdio".into(),
            tools: vec!["puppeteer_navigate".into(), "puppeteer_screenshot".into(), "puppeteer_click".into(), "puppeteer_fill".into(), "puppeteer_select".into(), "puppeteer_hover".into(), "puppeteer_evaluate".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 30000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "brave-search".into(),
            version: "2024.11.0".into(),
            description: "Web and local search using Brave's Search API".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-brave-search".into()],
            transport: "stdio".into(),
            tools: vec!["brave_web_search".into(), "brave_local_search".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 33000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "gdrive".into(),
            version: "2024.11.0".into(),
            description: "File access and search capabilities for Google Drive".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-gdrive".into()],
            transport: "stdio".into(),
            tools: vec!["search".into(), "read_file".into()],
            resources: vec!["gdrive://".into()],
            prompts: vec![],
            tags: vec![],
            downloads: 16000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "google-maps".into(),
            version: "2024.11.0".into(),
            description: "Location services, directions, and place details via Google Maps".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-google-maps".into()],
            transport: "stdio".into(),
            tools: vec!["maps_geocode".into(), "maps_reverse_geocode".into(), "maps_search_places".into(), "maps_place_details".into(), "maps_distance_matrix".into(), "maps_directions".into(), "maps_elevation".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 14000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "sentry".into(),
            version: "2024.11.0".into(),
            description: "Retrieving and analyzing issues from Sentry.io".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-sentry".into()],
            transport: "stdio".into(),
            tools: vec!["list_issues".into(), "get_issue".into(), "search_issues".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 11000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "everart".into(),
            version: "2024.11.0".into(),
            description: "AI image generation using various models".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-everart".into()],
            transport: "stdio".into(),
            tools: vec!["generate_image".into(), "list_models".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 8000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "redis".into(),
            version: "2024.11.0".into(),
            description: "Interact with Redis key-value stores".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-redis".into()],
            transport: "stdio".into(),
            tools: vec!["get".into(), "set".into(), "delete".into(), "list_keys".into()],
            resources: vec!["redis://".into()],
            prompts: vec![],
            tags: vec![],
            downloads: 9500,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "modelcontextprotocol".into(),
            name: "aws-kb-retrieval".into(),
            version: "2024.11.0".into(),
            description: "Retrieval from AWS Knowledge Base using Bedrock Agent Runtime".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/modelcontextprotocol/servers-archived".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@modelcontextprotocol/server-aws-kb-retrieval".into()],
            transport: "stdio".into(),
            tools: vec!["retrieve".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 7000,
            created_at: None,
            updated_at: None,
        },

        // ── Third-party / community servers ──
        ServerEntry {
            id: None,
            owner: "brave".into(),
            name: "brave-search".into(),
            version: "1.0.0".into(),
            description: "Official Brave Search MCP server (replacement for archived reference server)".into(),
            author: "Brave Software".into(),
            license: "MIT".into(),
            repository: "https://github.com/brave/brave-search-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "brave-search-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["brave_web_search".into(), "brave_local_search".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 40000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "upstash".into(),
            name: "context7".into(),
            version: "1.0.0".into(),
            description: "Up-to-date code documentation for LLMs and AI code agents".into(),
            author: "Upstash".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/upstash/context7".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@upstash/context7-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["resolve-library-id".into(), "get-library-docs".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 25000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "executeautomation".into(),
            name: "playwright".into(),
            version: "1.0.0".into(),
            description: "Browser automation and testing using Playwright".into(),
            author: "ExecuteAutomation".into(),
            license: "MIT".into(),
            repository: "https://github.com/executeautomation/mcp-playwright".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@executeautomation/playwright-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["playwright_navigate".into(), "playwright_screenshot".into(), "playwright_click".into(), "playwright_fill".into(), "playwright_evaluate".into(), "playwright_console_logs".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 22000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "tavily".into(),
            name: "tavily".into(),
            version: "1.0.0".into(),
            description: "AI-optimized search engine with real-time web search and content extraction".into(),
            author: "Tavily".into(),
            license: "MIT".into(),
            repository: "https://github.com/tavily-ai/tavily-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "tavily-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["tavily_search".into(), "tavily_extract".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 18000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "supabase".into(),
            name: "supabase".into(),
            version: "1.0.0".into(),
            description: "Manage Supabase projects, databases, edge functions, and auth".into(),
            author: "Supabase".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/supabase-community/supabase-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "supabase-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["list_projects".into(), "get_project".into(), "execute_sql".into(), "apply_migration".into(), "list_edge_functions".into(), "deploy_edge_function".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 20000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "21st-dev".into(),
            name: "magic-mcp".into(),
            version: "1.0.0".into(),
            description: "Create crafted UI components inspired by the best 21st.dev design engineers".into(),
            author: "21st.dev".into(),
            license: "MIT".into(),
            repository: "https://github.com/21st-dev/magic-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@21st-dev/magic-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["create_component".into(), "inspect_component".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 15000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "apify".into(),
            name: "apify".into(),
            version: "1.0.0".into(),
            description: "Use 6,000+ pre-built cloud tools to extract data from websites, e-commerce, social media, and more".into(),
            author: "Apify".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/apify/apify-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "apify-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["apify_run_actor".into(), "apify_get_dataset".into(), "apify_list_actors".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 12000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "datastax".into(),
            name: "astra-db".into(),
            version: "1.0.0".into(),
            description: "Manage collections and documents in DataStax Astra DB".into(),
            author: "DataStax".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/datastax/astra-db-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@datastax/astra-db-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["create_collection".into(), "insert_document".into(), "find_documents".into(), "update_document".into(), "delete_document".into(), "list_collections".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 10000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "zencoderai".into(),
            name: "slack".into(),
            version: "1.0.0".into(),
            description: "Slack MCP server maintained by Zencoder (successor to archived reference)".into(),
            author: "Zencoder".into(),
            license: "MIT".into(),
            repository: "https://github.com/zencoderai/slack-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@zencoderai/slack-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["list_channels".into(), "post_message".into(), "reply_to_thread".into(), "get_channel_history".into(), "search_messages".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 8000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "apollographql".into(),
            name: "apollo-mcp-server".into(),
            version: "1.0.0".into(),
            description: "Connect your GraphQL APIs to AI agents".into(),
            author: "Apollo GraphQL".into(),
            license: "MIT".into(),
            repository: "https://github.com/apollographql/apollo-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@apollo/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["execute_graphql".into(), "introspect_schema".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 7000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "cloudflare".into(),
            name: "cloudflare".into(),
            version: "1.0.0".into(),
            description: "Deploy and manage Cloudflare Workers, KV, R2, and D1 resources".into(),
            author: "Cloudflare".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/cloudflare/mcp-server-cloudflare".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@cloudflare/mcp-server-cloudflare".into()],
            transport: "stdio".into(),
            tools: vec!["workers_list".into(), "workers_deploy".into(), "kv_list".into(), "kv_get".into(), "kv_put".into(), "r2_list_buckets".into(), "r2_get_object".into(), "d1_query".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 18000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "stripe".into(),
            name: "stripe-agent-toolkit".into(),
            version: "1.0.0".into(),
            description: "Interact with Stripe API for payments, customers, and subscriptions".into(),
            author: "Stripe".into(),
            license: "MIT".into(),
            repository: "https://github.com/stripe/agent-toolkit".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@stripe/mcp".into()],
            transport: "stdio".into(),
            tools: vec!["create_customer".into(), "list_customers".into(), "create_payment_intent".into(), "create_invoice".into(), "list_products".into(), "create_product".into(), "create_price".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 15000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "linear".into(),
            name: "linear".into(),
            version: "1.0.0".into(),
            description: "Project management and issue tracking via Linear API".into(),
            author: "Linear".into(),
            license: "MIT".into(),
            repository: "https://github.com/linear/linear-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@linear/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["create_issue".into(), "list_issues".into(), "update_issue".into(), "search_issues".into(), "list_projects".into(), "list_teams".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 14000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "exa".into(),
            name: "exa".into(),
            version: "1.0.0".into(),
            description: "AI-native search via Exa API with neural and keyword modes".into(),
            author: "Exa".into(),
            license: "MIT".into(),
            repository: "https://github.com/exa-labs/exa-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "exa-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["web_search".into(), "find_similar".into(), "get_contents".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 16000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "browserbase".into(),
            name: "stagehand".into(),
            version: "1.0.0".into(),
            description: "AI-powered browser automation by Browserbase".into(),
            author: "Browserbase".into(),
            license: "MIT".into(),
            repository: "https://github.com/browserbase/stagehand".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@browserbasehq/mcp-stagehand".into()],
            transport: "stdio".into(),
            tools: vec!["stagehand_navigate".into(), "stagehand_act".into(), "stagehand_extract".into(), "stagehand_observe".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 11000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "neon".into(),
            name: "neon".into(),
            version: "1.0.0".into(),
            description: "Manage Neon serverless Postgres databases, branches, and queries".into(),
            author: "Neon".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/neondatabase/mcp-server-neon".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@neondatabase/mcp-server-neon".into()],
            transport: "stdio".into(),
            tools: vec!["list_projects".into(), "create_project".into(), "execute_sql".into(), "create_branch".into(), "list_branches".into(), "get_connection_string".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 13000,
            created_at: None,
            updated_at: None,
        },
        // ── Additional community servers ──
        ServerEntry {
            id: None,
            owner: "anthropic".into(),
            name: "claude-code".into(),
            version: "1.0.0".into(),
            description: "MCP server for Claude Code — agentic coding assistant with file editing, shell access, and project understanding".into(),
            author: "Anthropic".into(),
            license: "MIT".into(),
            repository: "https://github.com/anthropics/claude-code".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@anthropic/claude-code-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["edit_file".into(), "read_file".into(), "run_command".into(), "search_codebase".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 35000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "vercel".into(),
            name: "vercel".into(),
            version: "1.0.0".into(),
            description: "Deploy, manage, and inspect Vercel projects and deployments".into(),
            author: "Vercel".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/vercel/vercel-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@vercel/mcp".into()],
            transport: "stdio".into(),
            tools: vec!["list_projects".into(), "deploy".into(), "get_deployment".into(), "list_domains".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 12000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "turso".into(),
            name: "turso".into(),
            version: "1.0.0".into(),
            description: "Manage Turso (libSQL) databases, organizations, and queries".into(),
            author: "Turso".into(),
            license: "MIT".into(),
            repository: "https://github.com/tursodatabase/turso-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@tursodatabase/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["list_databases".into(), "execute_query".into(), "create_database".into(), "list_organizations".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 8000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "resend".into(),
            name: "resend".into(),
            version: "1.0.0".into(),
            description: "Send and manage emails via the Resend API".into(),
            author: "Resend".into(),
            license: "MIT".into(),
            repository: "https://github.com/resendlabs/mcp-server-resend".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@resend/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["send_email".into(), "list_emails".into(), "get_email".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 6000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "docker".into(),
            name: "docker".into(),
            version: "1.0.0".into(),
            description: "Manage Docker containers, images, volumes, and networks".into(),
            author: "Docker".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/docker/mcp-server-docker".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@docker/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["list_containers".into(), "run_container".into(), "stop_container".into(), "list_images".into(), "build_image".into(), "list_volumes".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 15000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "grafana".into(),
            name: "grafana".into(),
            version: "1.0.0".into(),
            description: "Search dashboards, query data sources, and investigate incidents in Grafana".into(),
            author: "Grafana Labs".into(),
            license: "Apache-2.0".into(),
            repository: "https://github.com/grafana/mcp-grafana".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@grafana/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["search_dashboards".into(), "query_prometheus".into(), "query_loki".into(), "list_datasources".into(), "get_dashboard".into(), "list_alerts".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 9000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "firecrawl".into(),
            name: "firecrawl".into(),
            version: "1.0.0".into(),
            description: "Web scraping, crawling, and content extraction at scale".into(),
            author: "Firecrawl".into(),
            license: "MIT".into(),
            repository: "https://github.com/mendableai/firecrawl-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "firecrawl-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["scrape_url".into(), "crawl_site".into(), "search_web".into(), "extract_data".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 14000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "notion".into(),
            name: "notion".into(),
            version: "1.0.0".into(),
            description: "Interact with Notion workspaces, databases, pages, and blocks".into(),
            author: "Notion".into(),
            license: "MIT".into(),
            repository: "https://github.com/makenotion/notion-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@notionhq/mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["search_pages".into(), "create_page".into(), "update_page".into(), "query_database".into(), "create_database".into(), "append_blocks".into()],
            resources: vec![],
            prompts: vec!["summarize_page".into()],
            tags: vec![],
            downloads: 16000,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "figma".into(),
            name: "figma".into(),
            version: "1.0.0".into(),
            description: "Read Figma designs, inspect components, and extract design tokens".into(),
            author: "Figma".into(),
            license: "MIT".into(),
            repository: "https://github.com/nicholasgriffintn/figma-mcp-server".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "figma-mcp-server".into()],
            transport: "stdio".into(),
            tools: vec!["get_file".into(), "get_components".into(), "get_styles".into(), "get_images".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 8500,
            created_at: None,
            updated_at: None,
        },
        ServerEntry {
            id: None,
            owner: "smithery".into(),
            name: "fetch".into(),
            version: "1.0.0".into(),
            description: "Enhanced web fetching with JavaScript rendering and content extraction".into(),
            author: "Smithery".into(),
            license: "MIT".into(),
            repository: "https://github.com/nicholasgriffintn/fetch-mcp".into(),
            command: "npx".into(),
            args: vec!["-y".into(), "@nicholasgriffintn/fetch-mcp".into()],
            transport: "stdio".into(),
            tools: vec!["fetch_url".into(), "fetch_rendered".into()],
            resources: vec![],
            prompts: vec![],
            tags: vec![],
            downloads: 5000,
            created_at: None,
            updated_at: None,
        },
    ];

    // Auto-assign tags to all seed servers
    for server in &mut servers {
        if server.tags.is_empty() {
            server.tags = auto_tags(&server.owner, &server.name);
        }
    }

    servers
}

/// Categories for organizing servers in browse views.
pub fn server_category(owner: &str, name: &str) -> &'static str {
    match (owner, name) {
        (_, n) if n.contains("search") => "🔍 Search",
        (_, n) if ["filesystem", "git", "gdrive", "google-drive"].contains(&n) => "📁 Files & VCS",
        (_, n) if ["postgres", "sqlite", "redis", "astra-db", "neon"].contains(&n) => "🗄️ Databases",
        (_, n) if ["github", "gitlab", "linear", "sentry", "apollo-mcp-server"].contains(&n) => "🛠️ Dev Tools",
        (_, n) if ["slack", "discord"].contains(&n) => "💬 Communication",
        (_, n) if ["puppeteer", "playwright", "stagehand"].contains(&n) => "🌐 Browser Automation",
        (_, n) if ["memory", "sequentialthinking", "context7"].contains(&n) => "🧠 AI & Reasoning",
        (_, n) if ["time", "fetch", "everything", "google-maps"].contains(&n) => "⚙️ Utilities",
        (_, n) if ["cloudflare", "supabase", "vercel", "docker"].contains(&n) => "☁️ Cloud & Infrastructure",
        (_, n) if ["stripe-agent-toolkit", "everart", "magic-mcp", "apify"].contains(&n) => "💳 Commerce & Media",
        (_, n) if ["resend"].contains(&n) => "💬 Communication",
        (_, n) if ["turso"].contains(&n) => "🗄️ Databases",
        (_, n) if ["claude-code"].contains(&n) => "🛠️ Dev Tools",
        (_, n) if ["grafana"].contains(&n) => "📊 Observability",
        (_, n) if ["firecrawl"].contains(&n) => "🌐 Browser Automation",
        (_, n) if ["notion"].contains(&n) => "📝 Productivity",
        (_, n) if ["figma"].contains(&n) => "🎨 Design",
        ("modelcontextprotocol", _) => "📦 Reference",
        _ => "📦 Other",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_servers_not_empty() {
        let servers = default_servers();
        assert!(servers.len() >= 30, "Expected at least 30 seed servers, got {}", servers.len());
    }

    #[test]
    fn test_no_duplicate_owner_name() {
        let servers = default_servers();
        let mut seen = std::collections::HashSet::new();
        for s in &servers {
            let key = format!("{}/{}", s.owner, s.name);
            assert!(seen.insert(key.clone()), "Duplicate server: {key}");
        }
    }

    #[test]
    fn test_all_servers_have_required_fields() {
        for s in default_servers() {
            assert!(!s.owner.is_empty(), "Empty owner");
            assert!(!s.name.is_empty(), "Empty name for {}", s.owner);
            assert!(!s.version.is_empty(), "Empty version for {}/{}", s.owner, s.name);
            assert!(!s.description.is_empty(), "Empty description for {}/{}", s.owner, s.name);
            assert!(!s.command.is_empty(), "Empty command for {}/{}", s.owner, s.name);
            assert!(!s.repository.is_empty(), "Empty repository for {}/{}", s.owner, s.name);
        }
    }

    #[test]
    fn test_auto_tags_assigned() {
        let servers = default_servers();
        // All seed servers should now have tags
        for s in &servers {
            assert!(
                !s.tags.is_empty(),
                "Server {}/{} should have auto-assigned tags",
                s.owner,
                s.name
            );
        }
    }

    #[test]
    fn test_auto_tags_official() {
        let tags = auto_tags("modelcontextprotocol", "filesystem");
        assert!(tags.contains(&"official".to_string()));
        assert!(tags.contains(&"filesystem".to_string()));
    }

    #[test]
    fn test_auto_tags_database() {
        let tags = auto_tags("modelcontextprotocol", "postgres");
        assert!(tags.contains(&"database".to_string()));
        assert!(tags.contains(&"sql".to_string()));
    }

    #[test]
    fn test_auto_tags_browser() {
        let tags = auto_tags("modelcontextprotocol", "puppeteer");
        assert!(tags.contains(&"browser".to_string()));
        assert!(tags.contains(&"scraping".to_string()));
    }

    #[test]
    fn test_categories_assigned() {
        assert_eq!(server_category("modelcontextprotocol", "filesystem"), "📁 Files & VCS");
        assert_eq!(server_category("modelcontextprotocol", "postgres"), "🗄️ Databases");
        assert_eq!(server_category("modelcontextprotocol", "puppeteer"), "🌐 Browser Automation");
        assert_eq!(server_category("unknown", "something"), "📦 Other");
    }
}
